---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Heroku
      - run: [
          heroku config:set DISABLE_COLLECTSTATIC=1,
          git push heroku master,
          heroku run python manage.py migrate,
          heroku run 'bower install --config.interactive=false;grunt prep;python manage.py collectstatic --noinput',
          heroku config:unset DISABLE_COLLECTSTATIC,
          heroku run python manage.py collectstatic,
      ]
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test --verbosity 2 --force-color"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
